# Generated by Django 4.0.6 on 2022-07-16 08:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategoriya nomi')),
                ('nameru', models.CharField(max_length=50, verbose_name='Kategoriya nomi ruscha')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='category_photo/', verbose_name='rasm')),
                ('desc', models.TextField(blank=True, max_length=1500, verbose_name='Kategoriya haqida')),
                ('descru', models.TextField(blank=True, max_length=1500, verbose_name='Kategoriya haqida ruscha')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='SubKategoriya nomi')),
                ('nameru', models.CharField(max_length=100, verbose_name='SubKategoriya nomi ruscha')),
                ('slug', models.SlugField(max_length=10, unique=True, verbose_name='*')),
                ('image', models.ImageField(upload_to='sub_category_photo/', verbose_name='rasm')),
                ('desc', models.TextField(blank=True, max_length=1500, verbose_name='Kategoriya haqida')),
                ('descru', models.TextField(blank=True, max_length=1500, verbose_name='Kategoriya haqida ruscha')),
                ('category', models.ManyToManyField(to='info.category')),
            ],
            options={
                'verbose_name': 'SubKategoriya',
                'verbose_name_plural': 'SubKategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='MainDori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name="Preparatning savdo nomi ya'ni nomi:")),
                ('nameru', models.CharField(max_length=500, verbose_name="Ruscha Preparatning savdo nomi ya'ni nomi ruscha :")),
                ('image', models.ImageField(upload_to='info_photo/', verbose_name='rasm')),
                ('slug', models.SlugField(unique=True, verbose_name='*')),
                ('affective_stuff', ckeditor.fields.RichTextField(verbose_name="Ta'sir etuvchi moddalar:")),
                ('affective_stuffru', ckeditor.fields.RichTextField(verbose_name="Ruscha: Ta'sir etuvchi moddalar:")),
                ('size_of_drug', ckeditor.fields.RichTextField(verbose_name='Dori shakli:')),
                ('size_of_drugru', ckeditor.fields.RichTextField(verbose_name='Ruscha: Dori shakli:')),
                ('ingredients', ckeditor.fields.RichTextField(verbose_name='Tarkibi:')),
                ('ingredientsru', ckeditor.fields.RichTextField(verbose_name='Ruscha: Tarkibi:')),
                ('describtion', ckeditor.fields.RichTextField(verbose_name="Ta'rifi:")),
                ('describtionru', ckeditor.fields.RichTextField(verbose_name="Ruscha: Ta'rifi:")),
                ('what_can_drug_do', ckeditor.fields.RichTextField(verbose_name='Ruscha: Farmakoterapeftik guruhi:')),
                ('code_atx', models.CharField(max_length=50, verbose_name='Kod ATX:')),
                ('far_desc', ckeditor.fields.RichTextField(verbose_name='Farmakalogik xususiyati:')),
                ('far_descru', ckeditor.fields.RichTextField(verbose_name='Ruscha: Farmakalogik xususiyati:')),
                ('using', ckeditor.fields.RichTextField(verbose_name="Qo'llanishi:")),
                ('usingru', ckeditor.fields.RichTextField(verbose_name="Ruscha: Qo'llanishi:")),
                ('bad_side', ckeditor.fields.RichTextField(verbose_name="Nojo'ya ta'siri:")),
                ('bad_sideru', ckeditor.fields.RichTextField(verbose_name="Ruscha: Nojo'ya ta'siri:")),
                ('non_use', ckeditor.fields.RichTextField(verbose_name="Qo'llash mumkin bo'lmagan holatlar:")),
                ('non_useru', ckeditor.fields.RichTextField(verbose_name="Ruscha: Qo'llash mumkin bo'lmagan holatlar:")),
                ('react_drugs', ckeditor.fields.RichTextField(verbose_name="Dorilarning o'zaro ta'siri:")),
                ('react_drugsru', ckeditor.fields.RichTextField(verbose_name="Ruscha: Dorilarning o'zaro ta'siri:")),
                ('spec_direct', ckeditor.fields.RichTextField(verbose_name='Maxsus korsatmalar:')),
                ('spec_directru', ckeditor.fields.RichTextField(verbose_name='Ruscha: Maxsus korsatmalar:')),
                ('prod_drug', ckeditor.fields.RichTextField(verbose_name='Chiqarilish shakli:')),
                ('prod_drugru', ckeditor.fields.RichTextField(verbose_name='Ruscha: Chiqarilish shakli:')),
                ('keep', ckeditor.fields.RichTextField(verbose_name='Saqlash sharoiti:')),
                ('keepru', ckeditor.fields.RichTextField(verbose_name='Ruscha: Saqlash sharoiti:')),
                ('shelf_life', ckeditor.fields.RichTextField(verbose_name='Yaroqlilik muddati:')),
                ('shelf_liferu', ckeditor.fields.RichTextField(verbose_name='Ruscha: Yaroqlilik muddati:')),
                ('give', ckeditor.fields.RichTextField(verbose_name='Dorixonalarda berilish tartibi:')),
                ('giveru', ckeditor.fields.RichTextField(verbose_name='Ruscha: Dorixonalarda berilish tartibi:')),
                ('producer', ckeditor.fields.RichTextField(verbose_name='Ishlab chiqaruvchi:')),
                ('producerru', ckeditor.fields.RichTextField(verbose_name='Ruscha: Ishlab chiqaruvchi:')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='post sanasi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info.category', verbose_name='Kategoriya')),
                ('subcategory', models.ManyToManyField(to='info.subcategory')),
            ],
            options={
                'verbose_name': 'Dori',
                'verbose_name_plural': 'Dorilar',
            },
        ),
    ]
